### ISSUE TITLE
Unprotected Credentials

### ISSUE THREAD

**Issue by yashbhutoria** [ajeyamadhavarao/rebel#1]
https://github.com/ajeyamadhavarao/rebel/blob/759e938d5be630d2bc6efe52f856398b799f8843/hackjaipur.py#L6

Your credentials are out there in open. Revoke this application from your twitter account to prevent anyone from using these.

**Comment by ajeyamadhavarao** [comment]
I have edited the code and revoked the application from twitter. 
Thanks for letting me know.
